version: '3.6'

networks:
  default-network:
    driver: bridge
services:
  mysql:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - default-network
    ports:
      - 3306:3306