server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/aw_healthy_app?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  cloud:
    stream:
      bindings:
        appCreatedSupplier-out-0:
          destination: app.v1.event.app-created
        appUpdatedSupplier-out-0:
          destination: app.v1.event.app-updated